site_name: WWIV BBS 5.8
repo_url: https://github.com/wwivbbs/docs/
copyright: 2014+ WWIV Software Services
docs_dir: docs
theme: readthedocs
#google_analytics: ['UA-71826946-2', 'docs.wwivbbs.org']
source_suffix:
  '.rst': 'restructuredtext'
  '.txt': 'markdown'
  '.md': 'markdown'
extra_css: [extra.css]
markdown_extensions:
  - toc:
      permalink: True
      anchorlink: True
nav:
  - Home: index.md
  - Installation:
      - 'Windows Installation': install/win.md
      - 'Linux Installation': install/linux.md
      - 'Linux dosemu Settings': linux/dosemu_scripts.md
      - 'Upgrading from Previous Versions': install/upgrade.md
  - Basic Configuration:
      - 'wwivconfig': cfg/wwivconfig.md
      - 'wwiv.ini': cfg/wwivini.md
      - 'Other Config Files': cfg/config_files.md
      - 'Log Files': cfg/logfiles.md
      - 'Displaying Text': cfg/displaying_text.md
      - 'WWIVbasic Reference': cfg/wwivbasic.md
      - 'Linux dosemu Settings': linux/dosemu.md
      - 'Event Management': cfg/eventmgmt.md
      - 'ACS Reference': cfg/acs.md
  - Basic Use:
    - 'WFC Screen (Local Console)': wfc.md
    - 'Frequently Asked Questions (FAQ)': faq.md
    - 'wwivutil - WWIV Utility Program' : wwivutil.md
  - Connectivity:
    - 'wwivd': conn/telnet.md    
    - 'NET2BBS': conn/net2bbs.md
    - 'fail2ban IP blocking': conn/fail2ban.md
    - 'Telnet/SSH Clients': conn/clients.md
  - Menus:
    - 'Customizing' : menus/customizing.md
    - 'Commands' : menus/commands.md
    - 'Main Menu': menus/main.md
    - 'Messaging System': menus/message.md
    - 'User Preferences': menus/defaults.md
    - 'G-Files': menus/gfiles.md
    - 'File Transfers': menus/transfers.md
    - 'Slash Menu': menus/slash.md
    - 'SysOp Menu': menus/sysop.md
  - Networking:
    - 'WWIVnet': network/wwivnet.md
    - 'FTN Networks': network/ftn_nets.md
    - 'UseNet': network/usenet.md
    - 'Semaphore Files Used' : network/semaphores.md
    - 'NET37 User Documentation': archive/net37_docs.md
    - 'NET37 Technical Documentation': archive/net37_tec_docs.md
  - Chains (Doors):
    - 'Chains (Doors)': chains/doors.md
    - 'BBSlink': chains/bbslink.md
    - 'Darkness': chains/darkness.md
    - 'DoorMUD': chains/doormud.md
    - 'DoorParty': chains/doorparty.md
    - 'LORD': chains/lord.md
    - 'LORD2': chains/lord2.md
    - 'MechWars': chains/mechwars.md
    - 'NetFoss': chains/nf.md
    - 'Planets: The Exploration of Space': chains/doorteos.md
    - 'Replaceable Parameters': chains/parameters.md
    - 'SR Doors (SRE, BRE, etc)' : chains/srdoor.md
    - 'TradeWars2002': chains/tradewars2002.md
  - Editors:
    - 'Internal Editor' : editors/internal.md
    - 'WWIVEdit': editors/wwivedit.md
    - 'QuickBBS Editors': editors/quickbbs.md
  - Miscelaneous:
    - 'WWIV History': misc/history.md
    - 'WWIV Open Source Announcement': misc/wwiv_open_source_announcement.md
    - 'License': misc/license.md
    - 'WWIV BBS list': misc/bbslist.md
    - 'New SysOps Guide': misc/newsysop.md
    - 'links': misc/links.md
